import { Resend } from 'resend';
import { config } from '../config.js';
import type { SentinelAlert } from '../types.js';

let _resend: Resend | null = null;
function getResend(): Resend {
  if (!_resend) {
    _resend = new Resend(config.resend.apiKey || 're_placeholder');
  }
  return _resend;
}

export async function sendAlertEmail(
  alert: SentinelAlert,
  userEmail: string,
): Promise<boolean> {
  const confidenceLabel = alert.confidence === 'sourced-primary'
    ? 'Primary Source'
    : alert.confidence === 'reported-secondary'
      ? 'Secondary Source'
      : 'Unverified';

  const sourceLine = alert.sourceUrl
    ? `<a href="${alert.sourceUrl}">${alert.sourceTitle}</a>`
    : '<em>No source available</em>';

  const html = `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto;">
      <h2 style="color: #1a1a1a;">STRATEMARK Sentinel Alert</h2>
      <table style="width: 100%; border-collapse: collapse; margin: 16px 0;">
        <tr><td style="padding: 8px 0; color: #666;">Company</td><td style="padding: 8px 0; font-weight: bold;">${alert.companyName}</td></tr>
        <tr><td style="padding: 8px 0; color: #666;">Change Type</td><td style="padding: 8px 0;">${alert.changeType}</td></tr>
        <tr><td style="padding: 8px 0; color: #666;">Confidence</td><td style="padding: 8px 0;"><span style="background: ${alert.confidence === 'sourced-primary' ? '#d4edda' : alert.confidence === 'reported-secondary' ? '#fff3cd' : '#f8d7da'}; padding: 2px 8px; border-radius: 4px;">${confidenceLabel}</span></td></tr>
        <tr><td style="padding: 8px 0; color: #666;">Source</td><td style="padding: 8px 0;">${sourceLine}</td></tr>
      </table>
      <div style="background: #f8f9fa; padding: 16px; border-radius: 8px; margin: 16px 0;">
        <p style="margin: 0; line-height: 1.6;">${alert.summary}</p>
      </div>
      <p style="color: #999; font-size: 12px;">Generated by STRATEMARK Sentinel on ${new Date(alert.createdAt).toLocaleDateString()}</p>
    </div>
  `;

  try {
    await getResend().emails.send({
      from: config.resend.fromEmail,
      to: userEmail,
      subject: `[STRATEMARK] ${alert.companyName} — ${alert.changeType} detected`,
      html,
      text: `${alert.companyName} — ${alert.changeType}\nConfidence: ${confidenceLabel}\nSource: ${alert.sourceUrl ?? 'None'}\n\n${alert.summary}`,
    });
    return true;
  } catch {
    return false;
  }
}

export async function sendBatchAlerts(
  alerts: SentinelAlert[],
  userEmail: string,
): Promise<number> {
  let sent = 0;
  for (const alert of alerts) {
    const ok = await sendAlertEmail(alert, userEmail);
    if (ok) sent++;
  }
  return sent;
}
